# Generated by Django 3.0 on 2022-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='signUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=100)),
                ('number', models.PositiveIntegerField(default='')),
                ('password', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
